[project]
name = "aihelpers"
version = "0.1.0"
description = "Collection of scripts to help with AI work"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckduckgo-search",
    "playwright",
    "html5lib"
]
